name: Update GitHub stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@8614f3a61601854731381d853f8566867754a5ca  #v2.0.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&include_all_commits=false
          path: profile/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit stats card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update GitHub stats for $(date +'%Y-%m-%d')" || exit 0
          git push
